const data = [
  { valor: 'a' },
  { valor: 'b' },
  { valor: 'c' },
  { valor: 'd' },
  { valor: 'e' },
  { valor: 'f' },
  { valor: 'g' },
  { valor: 'h' },
  { valor: 'i' },
  { valor: 'j' },
  { valor: 'k' },
  { valor: 'l' },
  { valor: 'm' },
  { valor: 'n' },
  { valor: 'o' },
  { valor: 'p' },
  { valor: 'q' },
  { valor: 'r' },
  { valor: 's' },
  { valor: 't' },
  { valor: 'u' },
  { valor: 'v' },
  { valor: 'w' },
  { valor: 'x' },
  { valor: 'y' },
  { valor: 'z' }
]

export default data;
